# Generated by Django 5.0.4 on 2024-04-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('match_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
                ('source_service', models.CharField(max_length=50)),
                ('destination_service', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('service_id', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=50)),
                ('isrc', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('playlistsong_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonoshareapp.matchstatus')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonoshareapp.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonoshareapp.song')),
            ],
        ),
    ]
